import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';

import { Sidebar } from '@/widgets/Sidebar/ui';
import '@/shared/styles/globals.css';

import styles from './layout.module.css';

const outfit = Outfit({
  weight: ['300', '400', '500'],
  variable: '--font-primary',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={outfit.variable}>
        <div className={styles.bg} />
        <div className={styles.container}>
          <Sidebar />
          <main className={styles.content}>{children}</main>
        </div>
      </body>
    </html>
  );
}
